export {default as iconExplore} from './IconExplore';
export {default as iconPlay} from './IconPlay'
export {default as iconUsers} from './IconUsers'
export {default as iconOrder} from './IconOrder'
export {default as iconComment} from './IconComment'
export {default as iconStudy} from './IconStudy'
export {default as iconStar} from './IconStar'
export {default as iconEye} from './IconEye'
export {default as iconClock} from './IconClock'